# Generated by Django 5.2.15 on 2026-06-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuerChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_nif', models.CharField(max_length=16, unique=True)),
                ('last_huella', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VerifactuRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('alta', 'Alta'), ('anulacion', 'Anulación')], max_length=10)),
                ('issuer_nif', models.CharField(max_length=16)),
                ('issuer_name', models.CharField(default='', max_length=120)),
                ('num_serie', models.CharField(max_length=64)),
                ('fecha_expedicion', models.CharField(max_length=10)),
                ('tipo_factura', models.CharField(default='F1', max_length=4)),
                ('cuota_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_hora_gen', models.CharField(max_length=32)),
                ('huella', models.CharField(max_length=64)),
                ('previous_huella', models.CharField(blank=True, default='', max_length=64)),
                ('xml', models.TextField()),
                ('signed', models.BooleanField(default=False)),
                ('module_version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifactu_records', to='invoicing.invoice')),
                ('previous_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_records', to='compliance.verifacturecord')),
            ],
            options={
                'indexes': [models.Index(fields=['issuer_nif', 'id'], name='idx_verifactu_chain')],
                'constraints': [models.UniqueConstraint(fields=('issuer_nif', 'num_serie', 'record_type'), name='uniq_verifactu_issuer_numserie_type')],
            },
        ),
    ]
