# Generated by Django 5.2.15 on 2026-06-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('disabled', 'Disabled')], max_length=10)),
                ('estado', models.CharField(blank=True, default='', max_length=24)),
                ('aeat_code', models.CharField(blank=True, default='', max_length=16)),
                ('aeat_message', models.CharField(blank=True, default='', max_length=255)),
                ('csv', models.CharField(blank=True, default='', max_length=64)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('aeat_env', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_attempts', to='compliance.verifacturecord')),
            ],
            options={
                'indexes': [models.Index(fields=['record', 'status'], name='idx_submission_record')],
            },
        ),
    ]
