# Generated by Django 5.2.15 on 2026-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionattempt',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('disabled', 'Disabled'), ('cancelled', 'Cancelled')], max_length=10),
        ),
    ]
