# Generated by Django 5.2.15 on 2026-06-18 09:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issued', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_taxid', models.CharField(max_length=32)),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255)),
                ('irpf_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('taxable_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('iva_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('irpf_retention', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, default='', max_length=16)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.series'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('owner', 'prefix'), name='uniq_series_owner_prefix'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='uniq_invoice_series_number'),
        ),
    ]
