# Generated by Django 5.2.15 on 2026-06-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='annulled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrects', to='invoicing.invoice'),
        ),
    ]
