"""T-024 — rectificativa UI view tests (UC-004).

Covers the browser path that drives the shipped ``issue_rectificativa`` engine
(T-017): the detail-page entry link + pre-filled form (Req 1), the happy path that
issues into the ``R`` series and links the original (Req 2/3), the engine
``ValidationError`` rollback that burns no number (Req 4), and owner-scoping
(Req 8). Runs with ``AEAT_SUBMISSION_LIVE`` off (the default) → DISABLED outcome,
so no live AEAT call is made.
"""
from decimal import Decimal

from django.test import TestCase
from django.urls import reverse

import compliance
from compliance.tests.factories import ISSUER_NAME, ISSUER_NIF
from invoicing.models import Invoice, Series
from invoicing.tests.factories import make_series, make_user

FECHA_HORA = "2026-06-20T12:00:00+02:00"


def _issued_original(owner, lines=((1, "100.00", "21"),)):
    """An issued invoice owned by ``owner`` with an alta record to rectify."""
    from compliance.tests.factories import issued_invoice

    invoice = issued_invoice(series=make_series(owner=owner), lines=list(lines))
    compliance.generate_alta(
        invoice, issuer_nif=ISSUER_NIF, issuer_name=ISSUER_NAME, fecha_hora=FECHA_HORA
    )
    return invoice


def _payload(rows=(("Servicio corregido", "1", "80.00", "21"),), tipo="R1"):
    total = max(3, len(rows))
    data = {
        "issuer_name": "Ana Autónoma",
        "issuer_nif": ISSUER_NIF,
        "issuer_address": "C/ Sol 2",
        "issuer_email": "ana@example.com",
        "tipo_factura": tipo,
        "form-TOTAL_FORMS": str(total),
        "form-INITIAL_FORMS": "0",
        "form-MIN_NUM_FORMS": "0",
        "form-MAX_NUM_FORMS": "1000",
    }
    for i in range(total):
        desc, qty, price, iva = rows[i] if i < len(rows) else ("", "", "", "21")
        data[f"form-{i}-description"] = desc
        data[f"form-{i}-quantity"] = qty
        data[f"form-{i}-unit_price"] = price
        data[f"form-{i}-iva_rate"] = iva
    return data


class RectificativaViewTests(TestCase):
    def setUp(self):
        self.owner = make_user()
        self.client.force_login(self.owner)
        self.original = _issued_original(self.owner)

    def test_detail_shows_rectificar_link_for_issued_uncorrected(self):
        # Requirement 1 — the entry point appears on an issued, not-yet-corrected invoice.
        resp = self.client.get(reverse("invoicing:detail", args=[self.original.pk]))
        self.assertContains(resp, reverse("invoicing:rectificar", args=[self.original.pk]))

    def test_get_form_prefilled_from_original(self):
        # Requirement 1 — the form is pre-filled with the original's line items.
        resp = self.client.get(reverse("invoicing:rectificar", args=[self.original.pk]))
        self.assertEqual(resp.status_code, 200)
        formset = resp.context["formset"]
        self.assertEqual(formset.initial[0]["description"], "x")
        self.assertEqual(formset.initial[0]["iva_rate"], "21")

    def test_post_issues_rectificativa_in_R_series_and_links_original(self):
        # Requirement 2/3 — engine issues in the R series, links original, view redirects.
        resp = self.client.post(
            reverse("invoicing:rectificar", args=[self.original.pk]), _payload()
        )
        rect = Invoice.objects.exclude(pk=self.original.pk).get()
        self.assertRedirects(resp, reverse("invoicing:detail", args=[rect.pk]))
        self.assertEqual(rect.series.prefix, "R")
        self.assertTrue(rect.issued)
        self.assertEqual(rect.number, rect.series.last_number)
        self.assertEqual(rect.taxable_base, Decimal("80.00"))
        self.original.refresh_from_db()
        self.assertEqual(self.original.corrected_by_id, rect.id)
        # Requirement 3 — a rectificativa-type alta record was generated by the engine.
        self.assertTrue(rect.verifactu_records.exists())

    def test_engine_validationerror_rerenders_and_burns_no_number(self):
        # Requirement 4 — no filled line items → engine refuses, no R number consumed.
        resp = self.client.post(
            reverse("invoicing:rectificar", args=[self.original.pk]),
            _payload(rows=()),  # all blank rows
        )
        self.assertEqual(resp.status_code, 200)  # re-rendered, not redirected
        self.assertEqual(Invoice.objects.exclude(pk=self.original.pk).count(), 0)
        series = Series.objects.get(owner=self.owner, prefix="R")
        self.assertEqual(series.last_number, 0)
        self.original.refresh_from_db()
        self.assertIsNone(self.original.corrected_by_id)

    def test_already_corrected_invoice_offers_no_second_rectificativa(self):
        # Issue one rectificativa, then the original's detail no longer offers the link
        # and a fresh GET to the form redirects with a notice.
        self.client.post(
            reverse("invoicing:rectificar", args=[self.original.pk]), _payload()
        )
        resp = self.client.get(reverse("invoicing:rectificar", args=[self.original.pk]))
        self.assertRedirects(resp, reverse("invoicing:detail", args=[self.original.pk]))

    def test_cross_owner_is_404(self):
        # Requirement 8 — another owner's invoice is a 404 on GET and POST.
        other = make_user()
        self.client.force_login(other)
        url = reverse("invoicing:rectificar", args=[self.original.pk])
        self.assertEqual(self.client.get(url).status_code, 404)
        self.assertEqual(self.client.post(url, _payload()).status_code, 404)
        self.original.refresh_from_db()
        self.assertIsNone(self.original.corrected_by_id)
